"""
Legal disclaimers and compliance for engineering software
"""
from pydantic import BaseModel
from typing import Optional
from datetime import datetime


# SECURITY FIX: Use timezone-aware datetime
from app.core.datetime_utils import utc_now
class EngineeringDisclaimer(BaseModel):
    """Engineering software legal disclaimer"""
    version: str = "1.0"
    last_updated: str = utc_now().isoformat()
    disclaimer: str = """
    ENGINEERING SOFTWARE DISCLAIMER
    
    IMPORTANT: READ CAREFULLY BEFORE USING THIS SOFTWARE
    
    1. PROFESSIONAL RESPONSIBILITY
    This software is a computational tool intended to assist licensed professional engineers
    in structural analysis and design. It does NOT replace professional engineering judgment,
    experience, or responsibility.
    
    2. VERIFICATION REQUIRED
    All results generated by this software MUST be independently verified by a licensed
    professional engineer before use in any construction or design project. Users are
    responsible for validating all inputs, assumptions, and outputs.
    
    3. NO WARRANTY
    This software is provided "AS IS" without warranty of any kind, either expressed or
    implied, including but not limited to warranties of merchantability, fitness for a
    particular purpose, or non-infringement.
    
    4. LIMITATION OF LIABILITY
    In no event shall StruMind, its developers, or contributors be liable for any direct,
    indirect, incidental, special, exemplary, or consequential damages (including but not
    limited to procurement of substitute goods or services, loss of use, data, or profits,
    or business interruption) arising from the use of this software.
    
    5. CODE COMPLIANCE
    Users are responsible for ensuring compliance with all applicable building codes,
    standards, and regulations in their jurisdiction. This software implements various
    design codes but does not guarantee compliance with local requirements.
    
    6. LICENSED PROFESSIONAL REQUIRED
    This software should only be used by or under the direct supervision of licensed
    professional engineers. Final designs must be sealed by a licensed professional
    engineer in accordance with local regulations.
    
    7. ACCEPTANCE OF TERMS
    By using this software, you acknowledge that you have read, understood, and agree
    to be bound by these terms. If you do not agree, do not use this software.
    
    8. BETA SOFTWARE NOTICE
    This software is currently in BETA. Features may change, and additional testing
    and validation are ongoing. Use in production projects should be done with
    appropriate caution and verification.
    """


class LegalAcceptance(BaseModel):
    """User acceptance of legal terms"""
    user_id: int
    accepted_at: datetime
    disclaimer_version: str
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None


def get_engineering_disclaimer() -> EngineeringDisclaimer:
    """Get the current engineering disclaimer"""
    return EngineeringDisclaimer()


def create_acceptance_record(user_id: int, ip_address: Optional[str] = None, 
                            user_agent: Optional[str] = None) -> LegalAcceptance:
    """Create a legal acceptance record"""
    disclaimer = get_engineering_disclaimer()
    return LegalAcceptance(
        user_id=user_id,
        accepted_at=utc_now(),
        disclaimer_version=disclaimer.version,
        ip_address=ip_address,
        user_agent=user_agent
    )


# Additional compliance notices
GDPR_NOTICE = """
DATA PRIVACY NOTICE (GDPR Compliance)

We collect and process personal data in accordance with GDPR regulations.
Your data is used solely for providing structural engineering services.
You have the right to access, modify, or delete your data at any time.
Contact: privacy@strumind.com
"""

EXPORT_CONTROL_NOTICE = """
EXPORT CONTROL NOTICE

This software may be subject to export control regulations.
Users are responsible for compliance with all applicable export laws.
"""
